# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirQualityMonitoring_Proximity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream', '~> 4.0.0'
  pod 'Charts', '~> 3.6'

  # Pods for AirQualityMonitoring_Proximity

end
